"""Build a plain-English markdown report of an agent run — a shareable record
of what the team did.

A pure function over the run and its tasks: no model call, no database, no
network, so it works offline and is trivially testable. The report is assembled
from the run record the pipeline already writes, so it is always available, even
for a run whose workspace is long gone.

Design note: docs/architecture/RUN_REPORT.md.
"""

from engine.db.models import AgentRun, AgentTask


def _first_line(text: str | None, limit: int = 100) -> str:
    stripped = (text or "").strip()
    if not stripped:
        return ""
    line = stripped.splitlines()[0]
    return line if len(line) <= limit else line[: limit - 1] + "…"


def build_run_report(run: AgentRun, tasks: list[AgentTask], repo_url: str | None) -> str:
    """One markdown document summarizing a run: request, plan, per-task outcome,
    cost, and result. Defensive about unset fields so it works for a run in any
    state (a run that failed in planning has no tasks; a fresh one has no cost)."""
    done = sum(1 for task in tasks if task.status == "done")
    lines: list[str] = [
        f"# Run report — {_first_line(run.request) or 'agent run'}",
        "",
        f"- **Status:** {str(run.status).replace('_', ' ')}",
        f"- **Repository:** {repo_url or 'not connected'}",
        f"- **Tasks:** {done}/{len(tasks)} completed",
        (
            f"- **Cost:** ${float(run.total_cost_usd or 0):.4f} "
            f"({run.total_input_tokens or 0} input / {run.total_output_tokens or 0} output tokens)"
        ),
    ]
    if run.pr_url:
        lines.append(f"- **Pull request:** {run.pr_url}")
    if run.error:
        lines.append(f"- **Failed:** {run.error}")

    lines += ["", "## Request", "", (run.request or "").strip() or "_none_"]

    summary = run.plan.get("summary") if isinstance(run.plan, dict) else None
    if summary:
        lines += ["", "## Plan", "", str(summary).strip()]

    if tasks:
        lines += ["", "## Tasks", ""]
        for task in tasks:
            status = str(task.status).replace("_", " ")
            lines.append(f"{task.sequence}. **{task.title}** — _{task.role}_ · {status}")
            if task.result:
                lines.append(f"   - {str(task.result).strip()}")

    lines += ["", "---", "", "_Generated by ASEP from the run record._", ""]
    return "\n".join(lines)
