/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_v1_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_v1_conversations__conversation_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_v1_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide Run
         * @description The human approval gate: approve starts the work, reject ends the run.
         */
        post: operations["decide_run_v1_runs__run_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Diff
         * @description Everything the agents changed in the run's workspace since its base commit.
         */
        get: operations["get_run_diff_v1_runs__run_id__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Events
         * @description Live timeline: push each event as it lands, close when the run ends.
         *     Postgres is the record, Redis only wakes the stream — a missed ping costs
         *     one heartbeat of latency, never an event (RUN_EVENT_STREAMING.md).
         *
         *     Each message carries its event id, so a reconnecting EventSource resumes
         *     from Last-Event-ID; the `after` query parameter seeds a fresh start.
         */
        get: operations["stream_events_v1_runs__run_id__events_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Repositories */
        get: operations["list_repositories_v1_repositories_get"];
        put?: never;
        /** Connect Repository */
        post: operations["connect_repository_v1_repositories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Indexing */
        post: operations["start_indexing_v1_repositories__repository_id__index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Repository */
        get: operations["search_repository_v1_repositories__repository_id__search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Repository Graph */
        get: operations["repository_graph_v1_repositories__repository_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Github Webhook */
        post: operations["github_webhook_v1_webhooks_github_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}/work-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Work Items */
        get: operations["list_work_items_v1_repositories__repository_id__work_items_get"];
        put?: never;
        /** Create Work Item */
        post: operations["create_work_item_v1_repositories__repository_id__work_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}/work-items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Work Item */
        patch: operations["update_work_item_v1_repositories__repository_id__work_items__item_id__patch"];
        trace?: never;
    };
    "/v1/repositories/{repository_id}/work-items/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reorder Work Items
         * @description Set each item's board position from its index in `ordered_ids`.
         */
        post: operations["reorder_work_items_v1_repositories__repository_id__work_items_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}/roadmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Repository Roadmap
         * @description Scrum Master: turn a one-line goal into work items saved to the backlog.
         */
        post: operations["generate_repository_roadmap_v1_repositories__repository_id__roadmap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}/work-items/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Work Item Insights
         * @description Blocked items and the recommended next item — computed, never stored.
         */
        get: operations["work_item_insights_v1_repositories__repository_id__work_items_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Knowledge
         * @description Newest memories first; with `q`, the hybrid-recall ranking instead.
         */
        get: operations["list_knowledge_v1_repositories__repository_id__knowledge_get"];
        put?: never;
        /** Create Knowledge */
        post: operations["create_knowledge_v1_repositories__repository_id__knowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}/knowledge/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Knowledge
         * @description Memories that turn out to be wrong are deleted, not argued with.
         */
        delete: operations["delete_knowledge_v1_repositories__repository_id__knowledge__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description The repository's generated documents, newest first.
         */
        get: operations["list_documents_v1_repositories__repository_id__documents_get"];
        put?: never;
        /**
         * Generate Repository Document
         * @description Technical Writer: generate a document from the index and save it.
         */
        post: operations["generate_repository_document_v1_repositories__repository_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/repositories/{repository_id}/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_v1_repositories__repository_id__documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/provider-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Provider Keys */
        get: operations["list_provider_keys_v1_provider_keys_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/provider-keys/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Provider Key */
        put: operations["set_provider_key_v1_provider_keys__provider__put"];
        post?: never;
        /** Delete Provider Key */
        delete: operations["delete_provider_key_v1_provider_keys__provider__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BlockedItemOut */
        BlockedItemOut: {
            /**
             * Item Id
             * Format: uuid
             */
            item_id: string;
            /** Title */
            title: string;
            /** Waiting On */
            waiting_on: string[];
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Repository Id */
            repository_id?: string | null;
        };
        /** ConversationOut */
        ConversationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DecisionIn */
        DecisionIn: {
            /** Approved */
            approved: boolean;
        };
        /** DependencyGraph */
        DependencyGraph: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /** DiffOut */
        DiffOut: {
            /** Diff */
            diff: string;
        };
        /** DocumentIn */
        DocumentIn: {
            /** @default readme */
            kind: components["schemas"]["DocumentKind"];
        };
        /**
         * DocumentKind
         * @enum {string}
         */
        DocumentKind: "readme" | "api_reference" | "changelog" | "architecture";
        /** DocumentOut */
        DocumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Created By */
            created_by: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * Estimate
         * @description Relative size only — never a false-precision hour count.
         * @enum {string}
         */
        Estimate: "small" | "medium" | "large";
        /** EventOut */
        EventOut: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** Agent */
            agent: string | null;
            /** Task Id */
            task_id: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** GraphEdge */
        GraphEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /** GraphNode */
        GraphNode: {
            /** Path */
            path: string;
            /** Language */
            language: string;
            /** In Degree */
            in_degree: number;
            /** Out Degree */
            out_degree: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * KnowledgeItemIn
         * @description A hand-written memory. Decisions and outcomes are captured automatically
         *     by runs; the page adds notes and preferences (and corrections as notes).
         */
        KnowledgeItemIn: {
            /** @default note */
            kind: components["schemas"]["KnowledgeKind"];
            /** Title */
            title: string;
            /** Content */
            content: string;
        };
        /** KnowledgeItemOut */
        KnowledgeItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Source Run Id */
            source_run_id: string | null;
            /** Created By */
            created_by: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Score */
            score?: number | null;
        };
        /**
         * KnowledgeKind
         * @enum {string}
         */
        KnowledgeKind: "decision" | "outcome" | "preference" | "note";
        /** MessageOut */
        MessageOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Model */
            model: string | null;
            /** Citations */
            citations: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PlanInsightsOut */
        PlanInsightsOut: {
            /** Blocked */
            blocked: components["schemas"]["BlockedItemOut"][];
            recommended: components["schemas"]["WorkItemOut"] | null;
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "low" | "medium" | "high" | "critical";
        /** ProviderKeyIn */
        ProviderKeyIn: {
            /** Key */
            key: string;
        };
        /** ProviderKeyOut */
        ProviderKeyOut: {
            /** Provider */
            provider: string;
            /** Last4 */
            last4: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ReorderIn */
        ReorderIn: {
            /** Ordered Ids */
            ordered_ids: string[];
        };
        /** RepositoryIn */
        RepositoryIn: {
            /** Url */
            url: string;
        };
        /** RepositoryOut */
        RepositoryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Url */
            url: string;
            /** Status */
            status: string;
            /** Default Branch */
            default_branch: string;
            /** Last Indexed At */
            last_indexed_at: string | null;
            /** Chunks */
            chunks: number;
        };
        /** RoadmapIn */
        RoadmapIn: {
            /** Goal */
            goal: string;
        };
        /** RunCreate */
        RunCreate: {
            /** Request */
            request: string;
            /** Repository Url */
            repository_url: string;
            /** Max Cost Usd */
            max_cost_usd?: number | string | null;
        };
        /** RunDetailOut */
        RunDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Request */
            request: string;
            /** Repository Url */
            repository_url: string;
            /** Error */
            error: string | null;
            /** Pr Url */
            pr_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Plan */
            plan: {
                [key: string]: unknown;
            } | null;
            /** Tasks */
            tasks: components["schemas"]["TaskOut"][];
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Total Input Tokens */
            total_input_tokens: number;
            /** Total Output Tokens */
            total_output_tokens: number;
        };
        /** RunOut */
        RunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Request */
            request: string;
            /** Repository Url */
            repository_url: string;
            /** Error */
            error: string | null;
            /** Pr Url */
            pr_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** SearchHit */
        SearchHit: {
            /** Path */
            path: string;
            /** Language */
            language: string;
            /** Start Line */
            start_line: number;
            /** End Line */
            end_line: number;
            /** Snippet */
            snippet: string;
            /** Score */
            score: number;
        };
        /** TaskOut */
        TaskOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Sequence */
            sequence: number;
            /** Role */
            role: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Status */
            status: string;
            /** Depends On */
            depends_on: string[];
            /** Result */
            result: string | null;
            /** Attempts */
            attempts: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkItemIn */
        WorkItemIn: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** @default feature */
            kind: components["schemas"]["WorkItemKind"];
            /** @default medium */
            priority: components["schemas"]["Priority"];
            estimate?: components["schemas"]["Estimate"] | null;
            /** Milestone */
            milestone?: string | null;
            /** Depends On */
            depends_on?: string[];
        };
        /**
         * WorkItemKind
         * @enum {string}
         */
        WorkItemKind: "feature" | "bug" | "chore" | "spike";
        /** WorkItemOut */
        WorkItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Repository Id
             * Format: uuid
             */
            repository_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Estimate */
            estimate: string | null;
            /** Priority */
            priority: string;
            /** Milestone */
            milestone: string | null;
            /** Depends On */
            depends_on: string[];
            /** Rationale */
            rationale: string | null;
            /** Position */
            position: number;
            /** Implemented By Run Id */
            implemented_by_run_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * WorkItemStatus
         * @enum {string}
         */
        WorkItemStatus: "proposed" | "ready" | "in_progress" | "blocked" | "done" | "cancelled";
        /**
         * WorkItemUpdate
         * @description Every field optional; only the fields sent are changed (partial update).
         */
        WorkItemUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            kind?: components["schemas"]["WorkItemKind"] | null;
            status?: components["schemas"]["WorkItemStatus"] | null;
            priority?: components["schemas"]["Priority"] | null;
            estimate?: components["schemas"]["Estimate"] | null;
            /** Milestone */
            milestone?: string | null;
            /** Depends On */
            depends_on?: string[] | null;
            /** Rationale */
            rationale?: string | null;
            /** Position */
            position?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    chat_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_v1_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"][];
                };
            };
        };
    };
    list_messages_v1_conversations__conversation_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_v1_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
        };
    };
    create_run_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_run_v1_runs__run_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_diff_v1_runs__run_id__diff_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_v1_runs__run_id__events_stream_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_repositories_v1_repositories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryOut"][];
                };
            };
        };
    };
    connect_repository_v1_repositories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_indexing_v1_repositories__repository_id__index_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_repository_v1_repositories__repository_id__search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repository_graph_v1_repositories__repository_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DependencyGraph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    github_webhook_v1_webhooks_github_post: {
        parameters: {
            query?: never;
            header?: {
                "x-github-event"?: string;
                "x-hub-signature-256"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_work_items_v1_repositories__repository_id__work_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_work_item_v1_repositories__repository_id__work_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkItemIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_work_item_v1_repositories__repository_id__work_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_work_items_v1_repositories__repository_id__work_items_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_repository_roadmap_v1_repositories__repository_id__roadmap_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoadmapIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    work_item_insights_v1_repositories__repository_id__work_items_insights_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanInsightsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_v1_repositories__repository_id__knowledge_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_knowledge_v1_repositories__repository_id__knowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeItemIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_knowledge_v1_repositories__repository_id__knowledge__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_v1_repositories__repository_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_repository_document_v1_repositories__repository_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_v1_repositories__repository_id__documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_provider_keys_v1_provider_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderKeyOut"][];
                };
            };
        };
    };
    set_provider_key_v1_provider_keys__provider__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderKeyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderKeyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_provider_key_v1_provider_keys__provider__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
