apiVersion: v1
kind: Service
metadata:
  name: {{ include "asep.fullname" . }}-web
  labels:
    {{- include "asep.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - port: 3000
      targetPort: 3000
